FROM jenkins/jenkins:lts

USER root

# Installer Python + pip + venv
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    pip3 install --upgrade pip --break-system-packages

# Install docker and docker-compose
RUN apt-get update && apt-get install -y docker.io docker-compose

RUN apt-get install -y git make

RUN apt-get install -y default-mysql-client

# Add jenkins user to the docker group
RUN usermod -aG docker jenkins

USER jenkins