FROM jenkins/jenkins:lts

USER root

# ARG to receive the GID from docker-compose
ARG DOCKER_GID

# Install dependencies in a single layer
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv docker.io docker-compose git make default-mysql-client && \
    rm -rf /var/lib/apt/lists/*

# Link python3 to python and upgrade pip
RUN ln -s /usr/bin/python3 /usr/bin/python && \
    pip3 install --upgrade pip --break-system-packages

# Modify the GID of the docker group to match the host's GID, if provided.
# The docker.io package creates the 'docker' group.
RUN if getent group docker > /dev/null && [ ! -z "$DOCKER_GID" ]; then \
    groupmod -g "$DOCKER_GID" docker; \
    fi

# Add jenkins user to the newly modified docker group
RUN usermod -aG docker jenkins

USER jenkins