FROM jenkins/jenkins:lts

USER root

# Installer Python + pip + venv
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-venv && \
    ln -s /usr/bin/python3 /usr/bin/python && \
    pip3 install --upgrade pip --break-system-packages

RUN apt-get install -y git make

RUN apt-get install -y default-mysql-client

# Copie ton script d’attente
COPY wait-for-it.sh /usr/local/bin/wait-for-it.sh
RUN chmod +x /usr/local/bin/wait-for-it.sh

USER jenkins